[features]
seeds = false
skip-lint = false
[programs.devnet]
network_cidadao = "Czu3SZdaZoHxX6X3yohJxnsGEuHNfy6frnAdJQYS6qHv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mknw/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
